const fs = require("fs/promises");
const path = require("path");
const { SQL_DIR } = require("../config");
const { query, withTransaction } = require("./client");
const { seedDatabase, ensureSeededAuthUsers, writeSeedCredentialsFile } = require("./seed");

async function applySchema() {
  const schemaProbe = await query(`
    SELECT EXISTS (
      SELECT 1
      FROM information_schema.tables
      WHERE table_schema = 'public'
        AND table_name = 'customers'
    ) AS exists
  `);

  if (schemaProbe.rows[0]?.exists) {
    return false;
  }

  const schemaPath = path.join(SQL_DIR, "schema.sql");
  const schemaSql = await fs.readFile(schemaPath, "utf-8");
  await query(schemaSql);
  return true;
}

async function seedIfEmpty() {
  const result = await query("SELECT COUNT(*)::int AS count FROM public.products");
  if (result.rows[0]?.count > 0) {
    return false;
  }

  await withTransaction(async (client) => {
    await seedDatabase(client);
  });

  return true;
}

async function ensureAuthSchema() {
  await query(`
    CREATE TABLE IF NOT EXISTS public.app_users (
      user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      username VARCHAR(50) NOT NULL UNIQUE,
      display_name VARCHAR(100) NOT NULL,
      role VARCHAR(20) NOT NULL CHECK (role IN ('client', 'admin', 'director', 'accountant', 'staff')),
      password_hash TEXT NOT NULL,
      access_code_hash TEXT,
      employee_id INTEGER REFERENCES public.employees(employee_id) ON DELETE SET NULL,
      customer_id INTEGER REFERENCES public.customers(customer_id) ON DELETE SET NULL,
      stock_access_enabled BOOLEAN NOT NULL DEFAULT FALSE,
      is_active BOOLEAN NOT NULL DEFAULT TRUE,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await query(`
    CREATE TABLE IF NOT EXISTS public.app_sessions (
      session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES public.app_users(user_id) ON DELETE CASCADE,
      token_hash VARCHAR(128) NOT NULL UNIQUE,
      session_scope VARCHAR(20) NOT NULL DEFAULT 'full' CHECK (session_scope IN ('full', 'stock_check')),
      expires_at TIMESTAMPTZ NOT NULL,
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
    )
  `);

  await query(`ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS access_code_hash TEXT`);
  await query(`ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS stock_access_enabled BOOLEAN NOT NULL DEFAULT FALSE`);
  await query(`ALTER TABLE public.app_users ADD COLUMN IF NOT EXISTS customer_id INTEGER REFERENCES public.customers(customer_id) ON DELETE SET NULL`);
  await query(`ALTER TABLE public.app_users DROP CONSTRAINT IF EXISTS app_users_role_check`);
  await query(
    `ALTER TABLE public.app_users ADD CONSTRAINT app_users_role_check CHECK (role IN ('client', 'admin', 'director', 'accountant', 'staff'))`
  );
  await query(
    `ALTER TABLE public.app_sessions ADD COLUMN IF NOT EXISTS session_scope VARCHAR(20) NOT NULL DEFAULT 'full'`
  );

  await query(`CREATE INDEX IF NOT EXISTS app_users_role_idx ON public.app_users(role)`);
  await query(`CREATE INDEX IF NOT EXISTS app_users_employee_idx ON public.app_users(employee_id)`);
  await query(`CREATE INDEX IF NOT EXISTS app_users_customer_idx ON public.app_users(customer_id)`);
  await query(`CREATE INDEX IF NOT EXISTS app_users_stock_access_idx ON public.app_users(stock_access_enabled)`);
  await query(`CREATE INDEX IF NOT EXISTS app_sessions_user_idx ON public.app_sessions(user_id)`);
  await query(`CREATE INDEX IF NOT EXISTS app_sessions_expires_idx ON public.app_sessions(expires_at)`);
  await query(`CREATE INDEX IF NOT EXISTS app_sessions_scope_idx ON public.app_sessions(session_scope)`);
}

async function ensureCartSchema() {
  await query(`
    CREATE TABLE IF NOT EXISTS public.cart_items (
      cart_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
      user_id INTEGER NOT NULL REFERENCES public.app_users(user_id) ON DELETE CASCADE,
      product_id INTEGER NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
      quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
      created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
      UNIQUE (user_id, product_id)
    )
  `);

  await query(`CREATE INDEX IF NOT EXISTS cart_items_user_idx ON public.cart_items(user_id)`);
  await query(`CREATE INDEX IF NOT EXISTS cart_items_product_idx ON public.cart_items(product_id)`);
}

async function bootstrapDatabase() {
  await applySchema();
  await ensureAuthSchema();
  await ensureCartSchema();
  await seedIfEmpty();
  const generatedCredentials = await withTransaction(async (client) => {
    return ensureSeededAuthUsers(client);
  });
  if (generatedCredentials) {
    await writeSeedCredentialsFile(generatedCredentials);
  }
}

module.exports = {
  bootstrapDatabase,
};
