DROP TABLE IF EXISTS public.app_sessions CASCADE;
DROP TABLE IF EXISTS public.app_users CASCADE;
DROP TABLE IF EXISTS public.activity_logs CASCADE;
DROP TABLE IF EXISTS public.user_sessions CASCADE;
DROP TABLE IF EXISTS public.complaints CASCADE;
DROP TABLE IF EXISTS public.comments CASCADE;
DROP TABLE IF EXISTS public.product_removal_requests CASCADE;
DROP TABLE IF EXISTS public.vendor_requests CASCADE;
DROP TABLE IF EXISTS public.global_settings CASCADE;
DROP TABLE IF EXISTS public.users CASCADE;

DROP TABLE IF EXISTS public.expenses CASCADE;
DROP TABLE IF EXISTS public.earnings CASCADE;
DROP TABLE IF EXISTS public.deliveries CASCADE;
DROP TABLE IF EXISTS public.order_payments CASCADE;
DROP TABLE IF EXISTS public.order_details CASCADE;
DROP TABLE IF EXISTS public.cart_items CASCADE;
DROP TABLE IF EXISTS public.product_service CASCADE;
DROP TABLE IF EXISTS public.employee_leaves CASCADE;
DROP TABLE IF EXISTS public.employee_resignations CASCADE;
DROP TABLE IF EXISTS public.monthly_profit CASCADE;
DROP TABLE IF EXISTS public.supplies CASCADE;
DROP TABLE IF EXISTS public.supplier_offers CASCADE;
DROP TABLE IF EXISTS public.orders CASCADE;
DROP TABLE IF EXISTS public.leave_types CASCADE;
DROP TABLE IF EXISTS public.suppliers CASCADE;
DROP TABLE IF EXISTS public.employees CASCADE;
DROP TABLE IF EXISTS public.customers CASCADE;
DROP TABLE IF EXISTS public.products CASCADE;

CREATE TABLE public.customers (
  customer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_name VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  phone VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  address VARCHAR(150),
  city VARCHAR(50),
  county VARCHAR(50),
  postal_code VARCHAR(20),
  registration_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE public.employees (
  employee_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  last_name VARCHAR(50) NOT NULL,
  first_name VARCHAR(50) NOT NULL,
  job_title VARCHAR(50),
  phone VARCHAR(20),
  email VARCHAR(100) UNIQUE,
  salary NUMERIC(10, 2),
  hire_date DATE
);

CREATE TABLE public.app_users (
  user_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  username VARCHAR(50) NOT NULL UNIQUE,
  display_name VARCHAR(100) NOT NULL,
  role VARCHAR(20) NOT NULL CHECK (role IN ('client', 'admin', 'director', 'accountant', 'staff')),
  password_hash TEXT NOT NULL,
  access_code_hash TEXT,
  employee_id INTEGER REFERENCES public.employees(employee_id) ON DELETE SET NULL,
  customer_id INTEGER REFERENCES public.customers(customer_id) ON DELETE SET NULL,
  stock_access_enabled BOOLEAN NOT NULL DEFAULT FALSE,
  is_active BOOLEAN NOT NULL DEFAULT TRUE,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.app_sessions (
  session_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.app_users(user_id) ON DELETE CASCADE,
  token_hash VARCHAR(128) NOT NULL UNIQUE,
  session_scope VARCHAR(20) NOT NULL DEFAULT 'full' CHECK (session_scope IN ('full', 'stock_check')),
  expires_at TIMESTAMPTZ NOT NULL,
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  last_seen_at TIMESTAMPTZ NOT NULL DEFAULT NOW()
);

CREATE TABLE public.leave_types (
  leave_type_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  code VARCHAR(10) NOT NULL UNIQUE,
  name VARCHAR(100) NOT NULL
);

CREATE TABLE public.suppliers (
  supplier_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  company_name VARCHAR(100) NOT NULL,
  contact_person VARCHAR(100),
  phone VARCHAR(20),
  email VARCHAR(100),
  address VARCHAR(150)
);

CREATE TABLE public.products (
  product_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  product_name VARCHAR(100) NOT NULL,
  brand VARCHAR(50),
  product_type VARCHAR(50),
  category VARCHAR(50),
  sale_price NUMERIC(10, 2) NOT NULL CHECK (sale_price >= 0),
  stock INTEGER DEFAULT 0 CHECK (stock >= 0),
  description TEXT,
  date_added DATE DEFAULT CURRENT_DATE
);

CREATE TABLE public.cart_items (
  cart_item_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  user_id INTEGER NOT NULL REFERENCES public.app_users(user_id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  quantity INTEGER NOT NULL DEFAULT 1 CHECK (quantity > 0),
  created_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  updated_at TIMESTAMPTZ NOT NULL DEFAULT NOW(),
  UNIQUE (user_id, product_id)
);

CREATE TABLE public.orders (
  order_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES public.customers(customer_id),
  employee_id INTEGER NOT NULL REFERENCES public.employees(employee_id),
  order_date DATE DEFAULT CURRENT_DATE,
  order_status VARCHAR(50),
  total_value NUMERIC(10, 2) DEFAULT 0 CHECK (total_value >= 0)
);

CREATE TABLE public.order_details (
  detail_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES public.products(product_id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  unit_price NUMERIC(10, 2) NOT NULL CHECK (unit_price >= 0),
  subtotal NUMERIC(10, 2) GENERATED ALWAYS AS ((quantity::numeric * unit_price)) STORED
);

CREATE TABLE public.order_payments (
  payment_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  payment_date DATE DEFAULT CURRENT_DATE,
  amount_paid NUMERIC(10, 2) NOT NULL CHECK (amount_paid >= 0),
  payment_method VARCHAR(50),
  payment_status VARCHAR(50)
);

CREATE TABLE public.deliveries (
  delivery_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  courier_company VARCHAR(100),
  awb_number VARCHAR(50) UNIQUE,
  delivery_cost NUMERIC(10, 2) CHECK (delivery_cost >= 0),
  delivery_address VARCHAR(200),
  shipping_date DATE,
  delivery_date DATE,
  delivery_status VARCHAR(50)
);

CREATE TABLE public.earnings (
  earning_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  order_id INTEGER NOT NULL REFERENCES public.orders(order_id) ON DELETE CASCADE,
  revenue NUMERIC(10, 2) CHECK (revenue >= 0),
  cost NUMERIC(10, 2) CHECK (cost >= 0),
  profit NUMERIC(10, 2),
  record_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE public.supplier_offers (
  offer_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES public.suppliers(supplier_id) ON DELETE CASCADE,
  product_id INTEGER NOT NULL REFERENCES public.products(product_id) ON DELETE CASCADE,
  available_quantity INTEGER CHECK (available_quantity >= 0),
  purchase_price NUMERIC(10, 2) CHECK (purchase_price >= 0)
);

CREATE TABLE public.supplies (
  supply_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  supplier_id INTEGER NOT NULL REFERENCES public.suppliers(supplier_id),
  product_id INTEGER NOT NULL REFERENCES public.products(product_id),
  quantity INTEGER NOT NULL CHECK (quantity > 0),
  purchase_price NUMERIC(10, 2) NOT NULL CHECK (purchase_price >= 0),
  supply_date DATE DEFAULT CURRENT_DATE
);

CREATE TABLE public.expenses (
  expense_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  expense_type VARCHAR(50),
  description TEXT,
  amount NUMERIC(10, 2) NOT NULL CHECK (amount >= 0),
  expense_date DATE DEFAULT CURRENT_DATE,
  supplier_id INTEGER REFERENCES public.suppliers(supplier_id),
  supply_id INTEGER REFERENCES public.supplies(supply_id),
  employee_id INTEGER REFERENCES public.employees(employee_id)
);

CREATE TABLE public.product_service (
  service_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  customer_id INTEGER NOT NULL REFERENCES public.customers(customer_id),
  product_id INTEGER NOT NULL REFERENCES public.products(product_id),
  order_id INTEGER REFERENCES public.orders(order_id),
  employee_id INTEGER REFERENCES public.employees(employee_id),
  received_date DATE DEFAULT CURRENT_DATE,
  reported_issue TEXT,
  diagnosis TEXT,
  service_status VARCHAR(50),
  solution VARCHAR(100),
  resolved_date DATE
);

CREATE TABLE public.employee_leaves (
  leave_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES public.employees(employee_id),
  leave_type VARCHAR(20) NOT NULL,
  start_date DATE NOT NULL,
  end_date DATE NOT NULL,
  reason TEXT,
  status VARCHAR(50)
);

CREATE TABLE public.employee_resignations (
  resignation_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  employee_id INTEGER NOT NULL REFERENCES public.employees(employee_id),
  resignation_date DATE NOT NULL,
  notice_period_days INTEGER,
  reason TEXT,
  status VARCHAR(50)
);

CREATE TABLE public.monthly_profit (
  profit_id INTEGER GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  month INTEGER NOT NULL CHECK (month BETWEEN 1 AND 12),
  year INTEGER NOT NULL CHECK (year >= 2000),
  total_earnings NUMERIC(12, 2) DEFAULT 0,
  total_expenses NUMERIC(12, 2) DEFAULT 0,
  net_profit NUMERIC(12, 2) DEFAULT 0,
  average_earnings NUMERIC(12, 2) DEFAULT 0,
  average_expenses NUMERIC(12, 2) DEFAULT 0,
  calculation_date DATE DEFAULT CURRENT_DATE,
  CONSTRAINT monthly_profit_unique_period UNIQUE (month, year)
);

CREATE INDEX customers_email_idx ON public.customers(email);
CREATE INDEX employees_email_idx ON public.employees(email);
CREATE INDEX app_users_role_idx ON public.app_users(role);
CREATE INDEX app_users_employee_idx ON public.app_users(employee_id);
CREATE INDEX app_users_customer_idx ON public.app_users(customer_id);
CREATE INDEX app_users_stock_access_idx ON public.app_users(stock_access_enabled);
CREATE INDEX app_sessions_user_idx ON public.app_sessions(user_id);
CREATE INDEX app_sessions_expires_idx ON public.app_sessions(expires_at);
CREATE INDEX app_sessions_scope_idx ON public.app_sessions(session_scope);
CREATE INDEX products_category_idx ON public.products(category);
CREATE INDEX products_type_idx ON public.products(product_type);
CREATE INDEX products_stock_idx ON public.products(stock);
CREATE INDEX cart_items_user_idx ON public.cart_items(user_id);
CREATE INDEX cart_items_product_idx ON public.cart_items(product_id);
CREATE INDEX orders_customer_idx ON public.orders(customer_id);
CREATE INDEX orders_employee_idx ON public.orders(employee_id);
CREATE INDEX orders_date_idx ON public.orders(order_date);
CREATE INDEX order_details_order_idx ON public.order_details(order_id);
CREATE INDEX order_details_product_idx ON public.order_details(product_id);
CREATE INDEX order_payments_order_idx ON public.order_payments(order_id);
CREATE INDEX deliveries_order_idx ON public.deliveries(order_id);
CREATE INDEX earnings_order_idx ON public.earnings(order_id);
CREATE INDEX supplier_offers_supplier_idx ON public.supplier_offers(supplier_id);
CREATE INDEX supplier_offers_product_idx ON public.supplier_offers(product_id);
CREATE INDEX supplies_supplier_idx ON public.supplies(supplier_id);
CREATE INDEX supplies_product_idx ON public.supplies(product_id);
CREATE INDEX expenses_supplier_idx ON public.expenses(supplier_id);
CREATE INDEX expenses_supply_idx ON public.expenses(supply_id);
CREATE INDEX expenses_employee_idx ON public.expenses(employee_id);
CREATE INDEX product_service_customer_idx ON public.product_service(customer_id);
CREATE INDEX product_service_product_idx ON public.product_service(product_id);
CREATE INDEX product_service_order_idx ON public.product_service(order_id);
CREATE INDEX product_service_employee_idx ON public.product_service(employee_id);
CREATE INDEX employee_leaves_employee_idx ON public.employee_leaves(employee_id);
CREATE INDEX employee_resignations_employee_idx ON public.employee_resignations(employee_id);
